version: "3.5"

services:
  homie-input:
    build:
      context: .
      dockerfile: Dockerfile
    image: rabarar/homie-input:0.1.7
    network_mode: "bridge"
    pid: "host"
    container_name: homie-input
    environment:
      - HOMIE_MQTT_USERNAME=admin
      - HOMIE_MQTT_PASSWORD=password
      - HOMIE_INFLUX_KEY=7jNY-tUAhBR9NVE0mcNieXLjthNxvzdklZQ7ZUboif6w4ID0qVHkwPrnpR2_LvGhlWCwBUeiwYmN7Fqt0y_bGg==
      - HOMIEGRAF_LEVEL=debug
    restart: always
